## What are Tensors?

Tensors are a fundamental data structure used in the field of Machine Learning and scientific computing.

In [1]:
import torch

In [2]:
# Using a List

lst = list(range(10))
print(f'List :{lst}')

a = torch.tensor(lst)
print(f'Tourch Tensor: {a}')

List :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Tourch Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10108\1248768064.py:6: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  a = torch.tensor(lst)


In [3]:
# Creating a 2D tensor (matrix)

tensor_2d = torch.tensor([[1,2,3],
                          [4,5,6]])

# Creating a 3D tensor
tensor_3d = torch.tensor([[[1,2,3],
                           [4,5,6],
                           [7,8,9],
                           [10,11,12]]])

# Creating a 4D tensor
tensor_4d = torch.tensor([[[[1,2],
                            [3,4]],
                            [[5,6],
                            [7,8]]],
                            [[[9,10],
                            [11,12]],
                            [[13,14],
                            [15,16]]]])

In [4]:
# Print the tensors
print('2D Tensor (Matrix):')
print(tensor_2d)
print('Shape:', tensor_2d.shape)

print('\n3D Tensor (Matrix):')
print(tensor_3d)
print('Shape:', tensor_3d.shape)

print('\n4D Tensor (Matrix):')
print(tensor_4d)
print('Shape:', tensor_2d.shape)

2D Tensor (Matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

3D Tensor (Matrix):
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([1, 4, 3])

4D Tensor (Matrix):
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Shape: torch.Size([2, 3])


In [5]:
tensor_2d.dtype

torch.int64

In [8]:
# Using a Numpy Array
import numpy as np

np_array = np.array(list(range(10)))
print(f"Numpy array:{np_array} || datatype : {type(np_array)}")

# Convert NumPy array to PyTorch tensor
# torch_tensor = torch.tensor(np_array)

# or

torch_tensor = torch.from_numpy(np_array)
print(f"Torch Tensor:{torch_tensor} || datatype : {type(torch_tensor)}")

# Convert tensor to Numpy array
c = torch_tensor.numpy()
print(f"Numpy array:{c} || datatype : {type(c)}")

Numpy array:[0 1 2 3 4 5 6 7 8 9] || datatype : <class 'numpy.ndarray'>


RuntimeError: Numpy is not available